### ISSUE TITLE
Support For EDNS Client Subnet

### ISSUE THREAD

**Issue by CheRuisiBesares** [DNS-OARC/flamethrower#26]
Hi. Im currently doing some testing with `kdig` which is heavily reliant on the ability to set the EDNS client subnet per query. I would love for flamethrower to have a similar ability to set EDNS client subnet. Im not sure what path forward would be best but I can imagine a new generator or I can image it could be useful as an option for some/all of the existing generators. 

For the `FileQueryGenerator` it would be great to allow specification of ECS per line. If we had something like this it would allow a PowerDNS operator to create a flame manifest from a `rec_control dump-cache` very easily. When ECS is enabled the format for this dump is approximately: 

```example.com. 17 IN CNAME target.example.com. ; (Indeterminate) auth=1 4.1.0.0/21```

 with the last entry being the ECS. Link [here](https://doc.powerdns.com/recursor/manpages/rec_control.1.html#commands). This would allow for more realistic testing of the entire caching setup.

**Comment by weyrick** [comment]
added in #31
