### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by aiys0211** [DNS-OARC/flamethrower#34]
OS: CentOS Linux release 7.7.1908
cmake: 3.17.0-rc3
ldns: ldns-1.7.1
libuv: libuv-v1.35.0
openssl: openssl-1.1.1e
gcc: upgrade to gcc-8.4.0

cmake is happy:
-- The host system is: Linux-3.10.0-1062.18.1.el7.x86_64.
-- Project base dir is: /home/software/flamethrower-master
-- Configuring done
-- Generating done
-- Build files have been written to: /home/software/flamethrower-master/build

When I execute the make, it does not compile:
In file included from /home/software/flamethrower-master/flame/metrics.cpp:7:0:
/home/software/flamethrower-master/3rd/json/json.hpp:128:10: 错误：#error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
         #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
          ^
In file included from /home/software/flamethrower-master/3rd/uvw/uvw/resource.hpp:6:0,
                 from /home/software/flamethrower-master/3rd/uvw/uvw/handle.hpp:8,
                 from /home/software/flamethrower-master/3rd/uvw/uvw/async.hpp:7,
                 from /home/software/flamethrower-master/3rd/uvw/uvw.hpp:1,
                 from /home/software/flamethrower-master/flame/metrics.h:12,
                 from /home/software/flamethrower-master/flame/metrics.cpp:8:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:24:37: 错误：需要类型限定
     template<typename U, typename = std::enable_if_t<std::is_integral<U>::value>>
                                     ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:24:37: 错误：需要 ‘>’
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在成员函数‘bool uvw::Emitter<T>::Handler<E>::empty() const’中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:102:35: 错误：形参声明为‘auto’
             auto pred = [](auto &&element){ return element.first; };
                                   ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在 lambda 函数中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:102:52: 错误：‘element’在此作用域中尚未声明
             auto pred = [](auto &&element){ return element.first; };
                                                    ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在成员函数‘void uvw::Emitter<T>::Handler<E>::clear()’中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:110:39: 错误：形参声明为‘auto’
                 auto func = [](auto &&element){ element.first = true; };
                                       ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在 lambda 函数中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:110:49: 错误：‘element’在此作用域中尚未声明
                 auto func = [](auto &&element){ element.first = true; };
                                                 ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在成员函数‘void uvw::Emitter<T>::Handler<E>::erase(uvw::Emitter<T>::Handler<E>::Connection)’中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:131:39: 错误：形参声明为‘auto’
                 auto pred = [](auto &&element){ return element.first; };
                                       ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在 lambda 函数中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:131:56: 错误：‘element’在此作用域中尚未声明
                 auto pred = [](auto &&element){ return element.first; };
                                                        ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在成员函数‘void uvw::Emitter<T>::Handler<E>::publish(E, T&)’中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:141:47: 错误：形参声明为‘auto’
             auto func = [&event, &ref](auto &&element) {
                                               ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在 lambda 函数中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:142:24: 错误：‘element’在此作用域中尚未声明
                 return element.first ? void() : element.second(event, ref);
                        ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在成员函数‘void uvw::Emitter<T>::Handler<E>::publish(E, T&)’中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:152:37: 错误：形参声明为‘auto’
             onL.remove_if([](auto &&element){ return element.first; });
                                     ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在 lambda 函数中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:152:54: 错误：‘element’在此作用域中尚未声明
             onL.remove_if([](auto &&element){ return element.first; });
                                                      ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在成员函数‘uvw::Emitter<T>::Handler<E>& uvw::Emitter<T>::handler()’中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:181:29: 错误：‘make_unique’不是‘std’的成员
            handlers[type] = std::make_unique<Handler<E>>();
                             ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:181:55: 错误：expected primary-expression before ‘>’ token
            handlers[type] = std::make_unique<Handler<E>>();
                                                       ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:181:58: 错误：expected primary-expression before ‘)’ token
            handlers[type] = std::make_unique<Handler<E>>();
                                                          ^
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp: 在成员函数‘void uvw::Emitter<T>::clear()’中:
/home/software/flamethrower-master/3rd/uvw/uvw/emitter.hpp:286:33: 错误：形参声明为‘auto’

**Comment by weyrick** [comment]
Thanks for the report. I'm afraid this environment is probably just too old for us to support. Are you able to upgrade the compiler, or to run docker containers on the host? We should probably have cmake indicate failure on a minimum compiler version.

**Comment by aiys0211** [comment]
make docker image on docker hub and run docker containers on the host, flamethrower is greate performance tool!
