### ISSUE TITLE
IPv6 target address won't parse

### ISSUE THREAD

**Issue by Mno-hime** [DNS-OARC/flamethrower#56]
Target IPv6 address `fd92:7065:b8e:ffff::3` makes Flamethrower fail with `could not parse url: https://fd92:7065:b8e:ffff::3` on Fedora 32 with Flamethrower 0.11 with DoH compiled-in (but it fails even with DoH disabled in `cmake`). Flamethrower 0.10.2 is fine.
```
--class: "IN"
--dnssec: true
--help: false
--qps-flow: null
--targets: null
--version: false
-F: "inet6"
-M: "GET"
-P: "udp"
-Q: "10000"
-R: false
-T: "A"
-b: null
-c: "10"
-d: "1"
-f: "/home/newman/isc/tmp/output/query_datafile"
-g: "file"
-l: "0"
-n: "0"
-o: null
-p: "5300"
-q: "10"
-r: "test.com"
-t: "3"
-v: "99"
GENOPTS: []
TARGET: "fd92:7065:b8e:ffff::3"
could not parse url: https://fd92:7065:b8e:ffff::3
```
Looking at my `ip a` output, it looks like a valid IPv6 address:
```
$ ip a | grep fd92:7065:b8e:ffff::3
    inet6 fd92:7065:b8e:ffff::3/64 scope global 
```

**Comment by Mno-hime** [comment]
Yes, that worked, thanks!

**Comment by Mno-hime** [comment]
Is it possible to construct target in a way that is accepted by Flamethrower v0.10.2 and v0.11? `https://[fd92:7065:b8e:ffff::3]` works for v0.11 but it doesn't for 0.10.2 (`fd92:7065:b8e:ffff::3` does): `unable to resolve target address: https://[fd92:7065:b8e:ffff::3]`.

**Comment by weyrick** [comment]
Sorry, not that I know of - it was not an intentional change, would rather a side effect of landing DoH.
