### ISSUE TITLE
All queries are timing out

### ISSUE THREAD

**Issue by vivekgkwd** [DNS-OARC/flamethrower#58]
Hi,

We tried using the docker image with docker run and with kubernetes
but all our flames dns queries are timing out 
Below the output observed 
Am I missing something ?

D11-Vivekanand-Gaikwad:~ vivekanand$ nslookup google.com
Server:		10.20.0.2
Address:	10.20.0.2#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.8.14

D11-Vivekanand-Gaikwad:~ vivekanand$ docker run ns1labs/flame -l 10 google.com -Q 10 -t 10
binding to 0.0.0.0
flaming target(s) [172.217.8.14] on port 53 with 10 concurrent generators, each sending 10 queries every 1ms on protocol udp
query generator [static] contains 1 record(s)
rate limit @ 10 QPS (1 QPS per concurrent sender)
0.981109s: send: 0, avg send: 0, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 0, timeouts: 0
1.98136s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 0, timeouts: 0
2.98177s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 10, timeouts: 0
3.98268s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 20, timeouts: 0
4.98277s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 30, timeouts: 0
5.9833s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 40, timeouts: 0
6.98372s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 50, timeouts: 0
7.98373s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 60, timeouts: 0
8.98396s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 70, timeouts: 0
9.98093s: send: 10, avg send: 10, recv: 0, avg recv: 0, min/avg/max resp: 0/-nan/0ms, in flight: 80, timeouts: 0
stopping, waiting up to 10s for in flight to finish...

------
run id      : 7ffd66d800d0
run start   : 2020-12-02T10:51:20Z
runtime     : 19.9831 s
total sent  : 90
total rcvd  : 0
min resp    : 0 ms
avg resp    : -nan ms
max resp    : 0 ms
avg r qps   : 0
avg s qps   : 10
avg pkt     : 33.3 bytes
tcp conn.   : 0
timeouts    : 90 (100%)
bad recv    : 0
net errors  : 0

**Comment by weyrick** [comment]
Hello, your target server is `google.com` which is not a DNS server, it's a web server so it is not responding to the DNS queries.

**Comment by vivekgkwd** [comment]
Thanks weyrick, my bad
