### ISSUE TITLE
Make/tag a release

### ISSUE THREAD

**Issue by kbabioch** [DNS-OARC/flamethrower#6]
To make it easier to package this utility, git tags (and/or some official release(s)) would be helpful, so we can properly version the resulting package, just as any other piece of software.

**Comment by fcelda** [comment]
Thanks for urging us. We tagged [Flamethrower 0.9](https://github.com/DNS-OARC/flamethrower/releases/tag/v0.9) yesterday.

**Comment by SrX** [comment]
Hello, 
Please, can you tag/release the latest version of flamethrower again?
Thx.
