### ISSUE TITLE
Any plans for pre-built packages?

### ISSUE THREAD

**Issue by yantarou** [DNS-OARC/flamethrower#63]
Some other DNS tools at DNS-OARC are provided as pre-built packages (to be installed via the usual package managers):

https://dev.dns-oarc.net/packages/

Are there any plans to also provide pre-built Flamethrower packages?

This would be very helpful for environments where compiling from source or using Docker images is not an option.

**Comment by jelu** [comment]
Hi @yantarou, I just want to clarify that `flamethrower` is not a DNS-OARC project. It's a @ns1 project and managed by them, so they will need to decide if and how they want to provide packages.

We, DNS-OARC, hosts this project within our GitHub organization because it's a relevant DNS tool and relevant to our DNS community.

**Comment by weyrick** [comment]
Hi @yantarou, yes we may be able to provide binary packages soon. We are investigating the right work flows and tools for this now in the [pktvisor](https://github.com/ns1/pktvisor) project and I hope that we can use that experienced8 to provide flamethrower packages as well.

**Comment by weyrick** [comment]
Would an AppImage (static linux binary) work, or do you require specific distro packages?

**Comment by yantarou** [comment]
Hi @weyrick. Sorry for the late reply..
I have never used AppImage, so cannot comment on that.
But from what's written on their homepage it sounds to be a feasible approach.
Anyway, I solved the issue for that particular environment in the meanwhile, thus from my side this issue can be closed.
It may make sense for others though to have an option besides Docker and compiling from source.

**Comment by pemensik** [comment]
I think it would be better, if packages were available in distribution packages or common additional packages for distribution (Extra Packages for Enterprise Linux alias EPEL for RHEL/CentOS). It would be nice @yantarou, if you would say what distribution packages are missing. I guess flatpak packages could be made also made, but first it should be known where are packages missing the most. I admit I am surprised [flamethrower package on Debian](https://packages.debian.org/sid/flamethrower) is a completely different thing.

**Comment by yantarou** [comment]
Let me close this stale ticket.
