### ISSUE TITLE
Flamethrower fails to build on Ubuntu 20.4

### ISSUE THREAD

**Issue by GuilhermeUtech** [DNS-OARC/flamethrower#68]
Flamethrower 0.10.2 (as well as master) fails to build for me on Ubuntu 20.4  with GCC:

Cmake step works fine

`guilherme@guilherme-System-Product-Name:~/Área de Trabalho/flamethrower/build$ cmake ..
-- No build type defined; defaulting to 'Debug'
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The host system is: Linux-5.8.0-53-generic.
-- Project base dir is: /home/guilherme/Área de Trabalho/flamethrower
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for one of the modules 'libldns;ldns'
-- Checking for module 'libuv>=1.23'
--   Found libuv, version 1.34.2
-- Checking for module 'gnutls>=3.3'
--   Found gnutls, version 3.6.13
-- DNS over HTTPS (DoH) support is disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/guilherme/Área de Trabalho/flamethrower/build`

Make doesn't work

`guilherme@guilherme-System-Product-Name:~/Área de Trabalho/flamethrower/build$ make
Scanning dependencies of target flamecore
[  7%] Building CXX object CMakeFiles/flamecore.dir/flame/metrics.cpp.o
In file included from /usr/include/c++/9/string_view:40,
             	from /usr/include/c++/9/bits/basic_string.h:48,
             	from /usr/include/c++/9/string:55,
             	from /usr/include/c++/9/bits/locale_classes.h:40,
             	from /usr/include/c++/9/bits/ios_base.h:41,
             	from /usr/include/c++/9/ios:42,
             	from /usr/include/c++/9/ostream:38,
             	from /usr/include/c++/9/iostream:39,
             	from /home/guilherme/Área de Trabalho/flamethrower/flame/metrics.cpp:4:
/usr/include/c++/9/limits:1665:7: internal compiler error: Instrução ilegal
 1665 |   	min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
  	|   	^~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/flamecore.dir/build.make:63: CMakeFiles/flamecore.dir/flame/metrics.cpp.o] Erro 1
make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/flamecore.dir/all] Erro 2
make: *** [Makefile:130: all] Erro 2
`

**Comment by weyrick** [comment]
hi @GuilhermeUtech, thanks for the report. Wow, an internal compiler error! We'll have to dig into this one a bit to see what's causing it.

**Comment by weyrick** [comment]
FYI I can't reproduce on 20.10 ... I do not have access to 20.4 at the moment. Is it possible you are compiling on a VM with very low memory?

**Comment by weyrick** [comment]
I've now confirmed it builds ok on 20.4 as well. Please check your memory constraints.

**Comment by GuilhermeUtech** [comment]
Hello Shanon, 
I've create a VM using ubuntu 20.10 and the installation works fine. 
I don't know what happened in 20.04, I didn't have memory constraints (8gb of mem available).
Thanks for your support, have a nice day :-)
