### ISSUE TITLE
how to run flame on centos7?

### ISSUE THREAD

**Issue by linydquantil** [DNS-OARC/flamethrower#79]
i download flame bin file from docker image. and copy it to centos7 sever.
after that i install some rpm packages: 
```
yum install libuv libuv-devel ldns-devel ldns -y
```
but i found some errors:
```
./flame: error while loading shared libraries: libldns.so.2: cannot open shared object file: No such file or directory
```
hi @weyrick , how to solve the problem?

**Comment by weyrick** [comment]
Hi @linydquantil, I'm sorry but I don't think removing the binary from the docker image will work. If you are unable to run the docker image or build it yourself, I'm afraid we don't have official centos packages so it may not work. 

I do still expect us to get an AppImage binary available in the future which may work.

**Comment by linydquantil** [comment]
Thank you for your reply.
