### ISSUE TITLE
Does not compile with the existing cmake instructions 

### ISSUE THREAD

**Issue by bortzmeyer** [DNS-OARC/flamethrower#91]
With the documented instructions, build fails:

```
% make
make: *** No targets specified and no makefile found.  Stop.
```

I believe the cmake call should be, instead of `cmake ..`, something like `cmake -S .. -B .`.

**Comment by bortzmeyer** [comment]
I mean:

```
cmake -S .. -B .
```

The final dot was confusing :-}

**Comment by weyrick** [comment]
Ok I do believe the build is working ok.
