### ISSUE TITLE
PTR qtype mapping incorrect

### ISSUE THREAD

**Issue by jamesph3** [DNS-OARC/flamethrower#96]
I was testing with PTR records and noticed they were coming through as AAAA. I can see in the qtype.cpp the PTR qtype is mapped to AAAA:

    } else if (qt == "PTR") {
        qtype = LDNS_RR_TYPE_AAAA;
    } else if (qt == "TXT") {

Should this be updated and mapped to LDNS_RR_TYPE_PTR?

**Comment by weyrick** [comment]
Yes, looks like simple copy and paste error. Can you create a quick PR for this? Thanks!

**Comment by jamesph3** [comment]
PR created...

**Comment by weyrick** [comment]
Thanks!
